/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Ticket;
import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.*;

public class App {


    public static void main(String[] args) {
        System.out.println("Running Train Booking system");
        Scanner sc=new Scanner(System.in);
        int option=0;
        UserBookingService userBookingService;
        Train trainSelectedForBooking=new Train();
        try{
            userBookingService=new UserBookingService();

        } catch (IOException e) {
            System.out.println("There is something wrong");
            return;
        }
        while(option!=7)
        {
            System.out.println("Choose Option");
            System.out.println("1. Sign Up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a seat");
            System.out.println("6. Cancel My Booking");
            System.out.println("7. Exit the app");
            option=sc.nextInt();
            switch (option){
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignUp=sc.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignUp=sc.next();
                    User userToSignUp=new User(nameToSignUp,passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp)
                            ,UUID.randomUUID().toString(),new ArrayList<Ticket>());
                    userBookingService.signUp(userToSignUp);
                    break;
                case 2:
                    System.out.println("Enter the username to login");
                    String nameToLogin=sc.next();
                    System.out.println("Enter the password to login");
                    String passwordToLogin=sc.next();
                    User userToLogin=new User(nameToLogin,passwordToLogin, UserServiceUtil.hashPassword(passwordToLogin), UUID.randomUUID().toString(),new ArrayList<>());
                    try{
                        userBookingService=new UserBookingService(userToLogin);
                    } catch (IOException e) {
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching your bookings");
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    System.out.println("Type your source station");
                    String source=sc.next();
                    System.out.println("Type your destination station");
                    String destination=sc.next();
                    List<Train> trains=userBookingService.getTrains(source,destination);
                    int index=1;
                    for(Train t:trains){
                        System.out.println(index+" Train id "+t.getTrainId());
                        for(Map.Entry<String,Date> entry:t.getStationTimes().entrySet()){
                            System.out.println("Station: "+entry.getKey()+" time: "+entry.getValue());
                        }
                    }
                    System.out.println("Select a train by typing 1 2 3");
                    trainSelectedForBooking=trains.get(sc.nextInt());
                    

            }
        }


    }
}
